# Generated by Django 6.0 on 2025-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('classroom', 'Classroom'), ('events', 'Events'), ('activities', 'Activities'), ('others', 'Others')], max_length=20)),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Check to show this image on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
