# Generated by Django 6.0 on 2025-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('local_government_area', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('home_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('first_language', models.CharField(blank=True, max_length=50, null=True)),
                ('proposed_year_of_entry', models.IntegerField()),
                ('current_school_name', models.TextField(blank=True, max_length=100, null=True)),
                ('current_class', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_title', models.CharField(blank=True, max_length=10)),
                ('father_profession', models.CharField(blank=True, max_length=100)),
                ('father_employer', models.TextField(blank=True)),
                ('father_phone', models.CharField(max_length=20)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_local_govt', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_title', models.CharField(blank=True, max_length=10)),
                ('mother_profession', models.CharField(blank=True, max_length=100)),
                ('mother_employer', models.TextField(blank=True)),
                ('mother_phone', models.CharField(max_length=20)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_local_govt', models.CharField(blank=True, max_length=100)),
                ('parents_address', models.TextField(blank=True)),
                ('life_threatening_condition', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('condition_details', models.TextField(blank=True)),
                ('medication_needed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('medication_details', models.TextField(blank=True)),
                ('other_medical_issues', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
