# Generated by Django 5.1 on 2026-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_admissionapplication_current_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
